name: Build Game Lag Switch Exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Bağımlılıkları önbelleğe alarak sonraki çalışmalarda hızı artırır

    - name: Bağımlılıkları Yükle
      run: |
        python -m pip install --upgrade pip
        pip install pydivert psutil keyboard pyinstaller

    - name: PyInstaller ile EXE'ye Dönüştür
      run: |
        pyinstaller --noconsole --onefile --uac-admin main.py

    - name: Hazır EXE Dosyasını GitHub'a Yükle (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Lag-Switch-Windows-Exe
        path: dist/main.exe
        
